

set(CPACK_GENERATOR "ZIP")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "sfeMovie SDK")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/License.txt")
set(CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/ReadMe.md")


set(CPACK_PACKAGE_VERSION_MAJOR "2")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_PACKAGE_NAME "${SFEMOVIE_LIB}-${CMAKE_BUILD_TYPE}")

if (NOT WINDOWS)
	set(CPACK_SET_DESTDIR TRUE)
endif()

set(CPACK_COMPONENTS_ALL doxygen binaries libraries resources)

include(CPack)
