

set(CPACK_GENERATOR "ZIP")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "sfeMovie SDK")
SET(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/License.txt")

SET(CPACK_PACKAGE_VERSION_MAJOR "2")
SET(CPACK_PACKAGE_VERSION_MINOR "0")
SET(CPACK_PACKAGE_VERSION_PATCH "0")

if (NOT WINDOWS)
	set(CPACK_SET_DESTDIR TRUE)
endif()

set(CPACK_COMPONENTS_ALL doxygen binaries libraries)

include(CPack)
